# _config.yml
# —————————————————————————————————————————————————————————————
# Basic site settings
title: “My GitHub Pages Site”
description: “A simple Jekyll site hosted on GitHub Pages.”
url: "https://dkim232.github.io"  # ← change this
baseurl: ""                               
# Theme & build settings
# theme: minima  # Commented out since using custom layout
markdown: kramdown
plugins:
  - jekyll-feed

# Optional: Uncomment to paginate blog posts
# paginate: 5
# paginate_path: "/page:num/"
# —————————————————————————————————————————————————————————————
